// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenSkinsApi.Infrastructure.Bus.Kafka.Events.Schemas.Auth.UserCreated
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;

	/// <summary>
	/// UserCreated event schema v1
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class UserCreated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""UserCreated"",""doc"":""UserCreated event schema v1"",""namespace"":""OpenSkinsApi.Infrastructure.Bus.Kafka.Events.Schemas.Auth.UserCreated"",""fields"":[{""name"":""UserId"",""type"":""string""},{""name"":""UserName"",""type"":""string""},{""name"":""FirstName"",""type"":""string""},{""name"":""LastName"",""type"":[""null"",""string""]}]}");
		private string _UserId;
		private string _UserName;
		private string _FirstName;
		private string _LastName;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return UserCreated._SCHEMA;
			}
		}
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				this._UserName = value;
			}
		}
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				this._FirstName = value;
			}
		}
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				this._LastName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
				case 0: return this.UserId;
				case 1: return this.UserName;
				case 2: return this.FirstName;
				case 3: return this.LastName;
				default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
				case 0: this.UserId = (System.String)fieldValue; break;
				case 1: this.UserName = (System.String)fieldValue; break;
				case 2: this.FirstName = (System.String)fieldValue; break;
				case 3: this.LastName = (System.String)fieldValue; break;
				default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
